version: 0.0
os: linux
files:
  - source: /
    destination: /data/
permissions:
  - object: /data/
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: root

